"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable max-line-length */
const models_1 = require("../../src/models");
exports.extensions = {
    default: {
        file: { icon: 'file', format: models_1.FileFormat.svg },
    },
    supported: [
        { icon: 'actionscript', extensions: ['as'], format: models_1.FileFormat.svg },
        {
            icon: 'ng_component_ts',
            extensions: ['component.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_component_js',
            extensions: ['component.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_controller_ts',
            extensions: ['controller.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_controller_js',
            extensions: ['controller.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_smart_component_ts',
            extensions: ['page.ts', 'container.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_smart_component_js',
            extensions: ['page.js', 'container.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_directive_ts',
            extensions: ['directive.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_directive_js',
            extensions: ['directive.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_pipe_ts',
            extensions: ['pipe.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_pipe_js',
            extensions: ['pipe.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_service_ts',
            extensions: ['service.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_service_js',
            extensions: ['service.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_module_ts',
            extensions: ['module.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_module_js',
            extensions: ['module.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_routing_ts',
            extensions: ['routing.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_routing_js',
            extensions: ['routing.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_routing_ts',
            extensions: ['app-routing.module.ts'],
            filename: true,
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_routing_js',
            extensions: ['app-routing.module.js'],
            filename: true,
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_component_ts2',
            extensions: ['component.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_component_js2',
            extensions: ['component.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_smart_component_ts2',
            extensions: ['page.ts', 'container.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_smart_component_js2',
            extensions: ['page.js', 'container.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_directive_ts2',
            extensions: ['directive.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_directive_js2',
            extensions: ['directive.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_pipe_ts2',
            extensions: ['pipe.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_pipe_js2',
            extensions: ['pipe.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_service_ts2',
            extensions: ['service.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_service_js2',
            extensions: ['service.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_module_ts2',
            extensions: ['module.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_module_js2',
            extensions: ['module.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_routing_ts2',
            extensions: ['routing.ts'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_routing_js2',
            extensions: ['routing.js'],
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_routing_ts2',
            extensions: ['app-routing.module.ts'],
            filename: true,
            format: models_1.FileFormat.svg,
            disabled: true,
        },
        {
            icon: 'ng_routing_js2',
            extensions: ['app-routing.module.js'],
            filename: true,
            format: models_1.FileFormat.svg,
            disabled: true,
        },
    ],
};
//# sourceMappingURL=supportedExtensions.js.map